#!/bin/bash
#SBATCH --job-name=runshapefunctions_array
#SBATCH --output=runshapefunctions_array_out_%A_%a.txt
#SBATCH --error=runshapefunctions_array_err_%A_%a.txt
#SBATCH --array=1-50
#SBATCH --account=lappi
#SBATCH --partition=small
#SBATCH --time=00:40:00
#SBATCH --ntasks=1
#SBATCH --mem-per-cpu=1000

module load julia
julia --project=. runshapefunctions.jl $SLURM_ARRAY_TASK_ID