#!/bin/bash
#SBATCH --account=lappi
#SBATCH --partition=test
#SBATCH --time=00:15:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=3
#SBATCH --mem-per-cpu=1000

module load julia
julia --project=. runshapefunctions.jl "/scratch/lappi/dana/test.jls"