#!/bin/bash
#SBATCH --job-name=runshapefunctions_array
#SBATCH --output=/scratch/lappi/dana/runshapefunctions_array_out_%A_%a.txt
#SBATCH --error=/scratch/lappi/dana/runshapefunctions_array_err_%A_%a.txt
#SBATCH --array=1-100
#SBATCH --account=lappi
#SBATCH --partition=small
#SBATCH --time=12:00:00
#SBATCH --ntasks=1
#SBATCH --mem-per-cpu=4000

module load julia
julia --project=. scripts/runshapefunctions.jl $SLURM_ARRAY_TASK_ID