#!/bin/bash
# This script is generated by generate_sbatch_jobs.jl. Do not edit manually.

#SBATCH --job-name=runshapefunctions
#SBATCH --output=/scratch/lappi/dana/slurm_out/runshapefunctions_out_%j.txt
#SBATCH --error=/scratch/lappi/dana/slurm_out/runshapefunctions_err_%j.txt
#SBATCH --account=lappi
#SBATCH --partition=small
#SBATCH --time=24:00:00
#SBATCH --ntasks=1
#SBATCH --mem-per-cpu=4000

module load julia

# Parameters
m=<m_value>
nmax=<nmax_value>
sigma_list=<sigma_list>
savepath=<savepath>
nconfigs=<nconfigs>
randomseed=$(date +%s%N) # random seed based on current date and time

# Loop through each configuration
for config_index in $(seq 0 $((nconfigs - 1))); do
    echo "Submitting job for config_index: $config_index"
    sbatch --wrap="julia --project=. scripts/runshapefunctions.jl $config_index $nconfigs $randomseed $m $nmax $savepath $sigma_list"
done